import lazy_loader


__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submodules={
        'agent',
        'data',
        'fitting',
        'simulation',
        'utils',
    },
    submod_attrs={
        'agent': [
            'base_agent',
            'model',
        ],
        'data': [
            'fetch_choices_and_rewards',
            'get',
        ],
        'fitting': [
            'aic',
            'bic',
            'cv',
            'evaluate_hierarchical_model',
            'evaluate_joint_model',
            'evaluate_model',
            'evaluation',
            'hierarchical',
            'hierarchical_train_model',
            'joint',
            'joint_train_model',
            'k_fold_cross_validation_train',
            'k_fold_cross_validation_train_hierarchical',
            'k_fold_cross_validation_train_joint',
            'k_fold_split_experiments',
            'k_fold_split_subjects',
            'likelihood_ratio_test',
            'log_likelihood_experiment',
            'multi_start_hierarchical_train',
            'multi_start_joint_train',
            'multi_start_train',
            'negative_log_likelihood_experiment',
            'total_negative_log_likelihood',
            'total_negative_log_likelihood_multi_group',
            'total_nll_hierarchical',
            'train',
            'train_model',
        ],
        'simulation': [
            'parse',
            'parse_reward_matrix',
            'simulate',
            'simulate_dataset',
            'simulate_dataset_different_params',
            'simulate_dataset_jit',
            'simulate_dataset_jit_different_params',
            'simulate_experiment',
            'simulate_experiment_jit',
        ],
        'utils': [
            'plot_experiment_data',
            'plot_training_history',
            'plotting',
        ],
    },
)

__all__ = ['agent', 'aic', 'base_agent', 'bic', 'cv', 'data',
           'evaluate_hierarchical_model', 'evaluate_joint_model',
           'evaluate_model', 'evaluation', 'fetch_choices_and_rewards',
           'fitting', 'get', 'hierarchical', 'hierarchical_train_model',
           'joint', 'joint_train_model', 'k_fold_cross_validation_train',
           'k_fold_cross_validation_train_hierarchical',
           'k_fold_cross_validation_train_joint', 'k_fold_split_experiments',
           'k_fold_split_subjects', 'likelihood_ratio_test',
           'log_likelihood_experiment', 'model',
           'multi_start_hierarchical_train', 'multi_start_joint_train',
           'multi_start_train', 'negative_log_likelihood_experiment', 'parse',
           'parse_reward_matrix', 'plot_experiment_data',
           'plot_training_history', 'plotting', 'simulate', 'simulate_dataset',
           'simulate_dataset_different_params', 'simulate_dataset_jit',
           'simulate_dataset_jit_different_params', 'simulate_experiment',
           'simulate_experiment_jit', 'simulation',
           'total_negative_log_likelihood',
           'total_negative_log_likelihood_multi_group',
           'total_nll_hierarchical', 'train', 'train_model', 'utils']
