# Book settings
title: FlYJAX
author: Rishika Mohanta
logo: logo.png

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: off

# Information about where the book exists on the web
repository:
  url: https://github.com/neurorishika/flYJAX 
  path_to_book: analysis  
  branch: master  

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

# Add parsing of myst markdown
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - substitution

# Add a table of contents
sphinx:
  extra_extensions:
    - autoapi.extension
  config:
    autoapi_dirs: ../flyjax
    autoapi_root: "reference"

